### ISSUE TITLE
Neutral analysis confusion

### ISSUE THREAD

**Issue by embaldridge** [weecology/sad-comparison#115]
Am I missing a dependency, or using an old version or something?  I did update macroecotools, so I know that's not it.  I'm also using the Enthought distribution on this machine, if I remember correctly.
[evaluate sad_neutral_analysis.py]
Importing Actinopterygii data
Traceback (most recent call last):
  File "/usr/lib/wingide-101-4.1/src/debug/tserver/_sandbox.py", line 69, in <module>
  File "/usr/lib/wingide-101-4.1/src/debug/tserver/_sandbox.py", line 34, in import_data
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 420, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 218, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 502, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 610, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 972, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/parser.so", line 330, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:2965)
  File "/usr/local/lib/python2.7/dist-packages/pandas-0.13.1-py2.7-linux-x86_64.egg/pandas/parser.so", line 557, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:5304)
IOError: File ./sad-data/chapter3/Actinopterygii_spab.csv

**Comment by ethanwhite** [comment]
I hadn't gotten the data files into the Dropbox folder yet. They should be syncing across now. I modified the headers from the White et al. 2012 files so that I could easily import them all into the same dataframe so I needed to make a new copy.

**Comment by embaldridge** [comment]
Yup, everything's fine now, and I can see what I was missing, now that I know it was asking me for files I didn't have.
